FROM golang:latest

ARG USERNAME=go

RUN useradd ${USERNAME} --create-home --user-group --shell /bin/bash

USER ${USERNAME}

ENV GOPATH=/home/${USERNAME}/utils/.go
ENV PATH=$GOPATH/bin:$PATH

RUN mkdir -p /home/${USERNAME}/.cache /home/${USERNAME}/utils/.go

WORKDIR /home/${USERNAME}
