FROM golang:latest

ARG USERNAME=go
ARG HOME=/home/go

RUN useradd ${USERNAME} --home-dir ${HOME} --create-home --user-group --shell /bin/bash

USER ${USERNAME}

ENV GOPATH=${HOME}/utils/.go
ENV PATH=$GOPATH/bin:$PATH
ENV GOOS=darwin

RUN mkdir -p ${HOME}/.cache ${HOME}/utils/.go

WORKDIR ${HOME}
