#!/bin/sh

source "$NOAHJAHN_UTILS_DIR/scripts/bash/base-image-tag.sh"
source "$NOAHJAHN_UTILS_DIR/scripts/bash/validate-binary.sh"
source "$NOAHJAHN_UTILS_DIR/scripts/bash/validate-input.sh"

id=$(_validate_binary uuidgen)
docker=$(_validate_binary docker)
printf=$(_validate_binary printf)

print_usage() {
    $printf "Usage:\tmysql-import\n\t\t-h <host>\n\t\t-P <port>\n\t\t-u <username>\n\t\t-p <password>\n\t\t-d <database-name>\n\t\t-f <file-name>\n\t\t-v <mysql-server-version>\n\n"
    $printf "\t-P\tport is optional, defaults to 3306\n"
    $printf "\t-v\tmysql-server-version is optional, defaults to latest\n"
}

parse_input() {
    while getopts 'h:P:u:p:d:f:v:' flag; do
        case "${flag}" in
        h) host="${OPTARG}" ;;
        P) port="${OPTARG}" ;;
        u) username="${OPTARG}" ;;
        p) password="${OPTARG}" ;;
        d) database="${OPTARG}" ;;
        f) file="${OPTARG}" ;;
        v) version="${OPTARG}" ;;
        esac
    done
}

host=
port='3306'
username=
password=
database=
file=
version='latest'

parse_input "$@"

_validate_input "$host" print_usage
_validate_input "$username" print_usage
_validate_input "$password" print_usage
_validate_input "$database" print_usage

IMAGE_TAG="$BASE_IMAGE_TAG-mysql-import"
CONTAINER_NAME="$IMAGE_TAG-$($id +%s)"

$docker run --name $CONTAINER_NAME --rm --entrypoint=tail -d mysql:$version -f /dev/null

$docker cp $file $CONTAINER_NAME:/$file

$docker exec -i $CONTAINER_NAME mysql --host $host --port $port --user $username -p$password -e 'SET FOREIGN_KEY_CHECKS=0;'
$docker exec -i $CONTAINER_NAME mysql --host $host --port $port --user $username -p$password $database <$file
$docker exec -i $CONTAINER_NAME mysql --host $host --port $port --user $username -p$password -e 'SET FOREIGN_KEY_CHECKS=1;'

$docker stop -t 1 $CONTAINER_NAME
