#!/bin/sh

HOST=
PORT='3306'
USERNAME=
PASSWORD=
DATABASE=
MYSQL_VERSION='8'
CHARSET='utf8'

print_usage() {
  printf "Usage:\tmysql-export\n\t\t-h <host>\n\t\t-P <port>\n\t\t-u <username>\n\t\t-p <password>\n\t\t-d <database-name>\n\t\t-v <mysql-server-version>\n\t\t-c <mysql-charset>\n\n"
  printf "\t-P\tport is optional, defaults to 3306\n"
  printf "\t-c\tmysql-charset is optional, defaults to utf8\n"
  printf "\t-v\tmysql-server-version is optional, defaults to 8\n"
}

while getopts 'h:P:u:p:d:v:c:' flag; do
  case "${flag}" in
    h) HOST="${OPTARG}" ;;
    P) PORT="${OPTARG}" ;;
    u) USERNAME="${OPTARG}" ;;
    p) PASSWORD="${OPTARG}" ;;
    d) DATABASE="${OPTARG}" ;;
    v) MYSQL_VERSION="${OPTARG}" ;;
    c) CHARSET="${OPTARG}" ;;
  esac
done

if [ -z "$HOST" ]; then
  print_usage
  exit 2;
fi

if [ -z "$USERNAME" ]; then
  print_usage
  exit 2;
fi

if [ -z "$PASSWORD" ]; then
  print_usage
  exit 2;
fi

if [ -z "$DATABASE" ]; then
  print_usage
  exit 2;
fi

docker run --rm --entrypoint=mysqldump mysql:$MYSQL_VERSION \
  --add-drop-table \
  --comments \
  --create-options \
  --dump-date \
  --no-autocommit \
  --routines \
  --default-character-set=$CHARSET \
  --set-charset \
  --triggers \
  --no-tablespaces \
  --set-gtid-purged=OFF \
  --no-data $DATABASE \
  --host $HOST \
  --port $PORT \
  --user $USERNAME \
  -p$PASSWORD > ./$DATABASE.sql

docker run --rm --entrypoint=mysqldump mysql:$MYSQL_VERSION \
  --add-drop-table \
  --comments \
  --create-options \
  --dump-date \
  --no-autocommit \
  --routines \
  --default-character-set=$CHARSET \
  --set-charset \
  --triggers \
  --no-tablespaces \
  --no-create-info \
  --set-gtid-purged=OFF \
  --host $HOST \
  --port $PORT \
  --user $USERNAME \
  -p$PASSWORD $DATABASE >> ./$DATABASE.sql
