#!/bin/sh

source "$NOAHJAHN_UTILS_DIR/scripts/bash/base-image-tag.sh"
source "$NOAHJAHN_UTILS_DIR/scripts/bash/validate-binary.sh"
source "$NOAHJAHN_UTILS_DIR/scripts/bash/validate-input.sh"

id=$(_validate_binary uuidgen)
docker=$(_validate_binary docker)
printf=$(_validate_binary printf)

print_usage() {
    $printf "Usage:\tpsql-export [OPTIONS]\n"
    $printf "\nExport a dump of a PostgreSQL database quickly and efficiently\n\n"
    $printf "Options:\n"
    $printf "  -h, --host string\t\tThe host of the database server you want to export from\n"
    $printf "  -p, --port int\t\tThe port of the database server you want to export from, defaults to 5432\n"
    $printf "  -u, --username string\t\tThe username of the database server that has access to the database that you want to export from\n"
    $printf "  -d, --database string\t\tThe database name on the database server that you want to export from\n"
    $printf "  -v, --version string\t\tThe PostgreSQL database version that you want to use for the pg_dump client, corresponds to the postgres docker image tag, defaults to latest\n"
}
parse_input() {
    while true; do
        case "$1" in
        -h | --host)
            host="$2"
            shift 2
            ;;
        -p | --port)
            port="$2"
            shift 2
            ;;
        -u | --username)
            username="$2"
            shift 2
            ;;
        -d | --database)
            database="$2"
            shift 2
            ;;
        -v | --version)
            version="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *) break ;;
        esac
    done
}

host=
port='5432'
username=
database=
file=
version='latest'

parse_input "$@"

_validate_input "$host" print_usage
_validate_input "$username" print_usage
_validate_input "$database" print_usage

IMAGE_TAG="$BASE_IMAGE_TAG-psql-export"
CONTAINER_NAME="$IMAGE_TAG-$($id +%s)"

$docker run --name $CONTAINER_NAME --rm --entrypoint=tail -d postgres:$version -f /dev/null

pg_dump_flags="--file /$database.sql \
    --host $host \
    --port $port \
    --user $username \
    --format=c \
    --section=pre-data \
    --section=data \
    --section=post-data \
    --no-owner \
    --no-privileges \
    --no-tablespaces \
    --no-unlogged-table-data \
    --no-comments \
    --no-publications \
    --no-subscriptions \
    --no-security-labels \
    --verbose"

if [ "$(echo "$version>=14" | bc -l)" -eq "1" ]; then
    pg_dump_flags="$pg_dump_flags \
        --no-toast-compression \
    "
fi

if [ "$(echo "$version>=16" | bc -l)" -eq "1" ]; then
    pg_dump_flags="$pg_dump_flags \
        --large-objects \
        --no-table-access-method \
    "
fi

$docker exec -it $CONTAINER_NAME pg_dump \
    $pg_dump_flags \
    $database \
    -W

$docker cp $CONTAINER_NAME:/$database.sql $database.sql

$docker stop -t 1 $CONTAINER_NAME
